version: "3.9"
services:
  # envoy:
  #   build:
  #     context: envoy
  #   ports:
  #     - 8080:8080
  #     - 9901:9901
  #   depends_on:
  #     - public-todo
  #     - public-auth
  #     - api-extauth
  #   networks:
  #     - dmz
  #     - frontend

  #
  #  Endpoints that are proxied through Envoy
  #
  public-todo:
    image: public-todo
    build:
      context: src/go
      dockerfile: cmd/compose/publicapi/todo/Dockerfile
    ports:
      - 14001:14586
    networks:
      - backend
      - dmz
    env_file: dev-variables.env

  public-auth:
    image: public-auth
    build:
      context: src/go
      dockerfile: cmd/compose/publicapi/auth/Dockerfile
    ports:
      - 14002:14586
    networks:
      - dmz
      - backend
    env_file: dev-variables.env
  #
  # The JWT Cookie validator for Envoy
  #
  # api-extauth:
  #   image: api-extauth
  #   build:
  #     context: src/go
  #     dockerfile: cmd/compose/middleware/extauth/Dockerfile
  #   ports:
  #     - 14010:14586
  #   networks:
  #     - dmz
  #   env_file: dev-variables.env

  #
  #  Backend services
  #
  core-user:
    image: core-user
    build:
      context: src/go
      dockerfile: cmd/compose/core/user/Dockerfile
    ports:
      - 13001:14586
    networks:
      - backend

  core-todo:
    image: core-todo
    build:
      context: src/go
      dockerfile: cmd/compose/core/todo/Dockerfile
    ports:
      - 13005:14586
    networks:
      - backend

  core-oauth-user:
    image: core-oauth-user
    build:
      context: src/go
      dockerfile: cmd/compose/core/oauth_user/Dockerfile
    ports:
      - 13002:14586
    networks:
      - backend
    environment:
      - GOOGLE_SECRET
      - GOOGLE_CLIENT_ID
    env_file: dev-variables.env

  core-workers:
    image: core-workers
    build:
      context: src/go
      dockerfile: cmd/compose/core/workers/Dockerfile
    env_file: dev-variables.env
    networks:
      - backend
    depends_on:
      - redis

  core-send-email:
    image: core-send-email
    build:
      context: src/go
      dockerfile: cmd/compose/core/send_email/Dockerfile
    environment:
      - SMTP_ADDR
      - SMTP_USERNAME
      - SMTP_PASSWORD
    env_file: dev-variables.env
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 36379:6379
    networks:
      - backend

  #
  #  React GUI
  #
  client:
    image: ts-client-react
    build:
      context: ts-client-react
    ports:
      - 8081:80
    links:
      - "public-auth:public-auth"
      - "public-todo:public-todo"
      # links:
      # - "envoy:backend"
      # depends_on:
      # - envoy
    networks:
      - frontend
      - dmz

networks:
  #
  #  Services that Envoy talks to
  #
  dmz: {}
  #
  #  Backend services
  #
  backend: {}
  #
  #  Backend services
  #
  frontend: {}
