version: "3.9"
services:
  envoy:
    build:
      context: envoy
    ports:
      - 8080:8080
      - 9901:9901
    depends_on:
      - public-todo
      - public-auth
      - api-extauth
    networks:
      - envoymesh

  #
  #  Endpoints that are proxied through Envoy
  #
  public-todo:
    image: public-todo
    build:
      context: src/go
      dockerfile: cmd/publicapi/todo/Dockerfile
    ports:
      - 14001:14586
    networks:
      - envoymesh
    env_file:
      dev-variables.env
  public-auth:
    image: public-auth
    build:
      context: src/go
      dockerfile: cmd/publicapi/auth/Dockerfile
    ports:
      - 14002:14586
    networks:
      - envoymesh
      - backend
    env_file:
      dev-variables.env
  #
  # The JWT Cookie validator for Envoy
  #
  api-extauth:
    image: api-extauth
    build:
      context: src/go
      dockerfile: cmd/middleware/extauth/Dockerfile
    ports:
      - 14010:14586
    networks:
      - envoymesh
    env_file:
      dev-variables.env

  #
  #  Backend services
  #
  core-user:
    image: core-user
    build:
      context: src/go
      dockerfile: cmd/core/user/Dockerfile
    ports:
      - 13001:14586
    networks:
      - backend

  core-workers:
    image: core-workers
    build:
      context: src/go
      dockerfile: cmd/core/workers/Dockerfile
    env_file:
      dev-variables.env
    networks:
      - backend

  core-send-email:
    image: core-send-email
    build:
      context: src/go
      dockerfile: cmd/core/send_email/Dockerfile
    environment:
      - SMTP_HOST
      - SMTP_USERNAME
      - SMTP_PASSWORD
    env_file:
      dev-variables.env
    networks:
      - backend

  redis:
    image: redis
    ports:
      - 36379:6379
    networks:
      - backend

  #
  #  React GUI
  #
  client:
    image: ts-client-react
    build:
      context: ts-client-react
    ports:
      - 8081:80
    depends_on:
      - envoy

networks:
  #
  #  Services that Envoy talks to
  #
  envoymesh: {}
  #
  #  Backend services
  #
  backend: {}
