FROM golang:1.17.1-alpine3.14 
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

EXPOSE 14586
CMD ["./tilt-scripts/start.sh", "go", "run", "-gcflags=-G=3", "cmd/core/oauth_user/main.go"]
