apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-variables-env
data:
  EMAILSERVICE_ADDR: core-send-email:14586
  OAUTH_USER_SERVICE_ADDR: core-oauth-user:14586
  REDIS_ADDR: redis:6379
  TODO_SERVICE_ADDR: core-todo:14586
  URL_BASE_UI: http://localhost:1234
  USER_SERVICE_ADDR: core-user:14586
  DYNAMO_STORE_ADDR: dynamodb:8000
