export type Colors =
  | "blueGray"
  | "gray"
  | "brown"
  | "deepOrange"
  | "orange"
  | "amber"
  | "yellow"
  | "lime"
  | "lightGreen"
  | "green"
  | "teal"
  | "cyan"
  | "lightBlue"
  | "blue"
  | "indigo"
  | "deepPurple"
  | "purple"
  | "pink"
  | "red";

export const filledBgColors: Record<Colors, string> = {
  blueGray: "bg-blue-gray-500",
  gray: "bg-gray-500",
  brown: "bg-brown-500",
  deepOrange: "bg-deep-orange-500",
  orange: "bg-orange-500",
  amber: "bg-amber-500",
  yellow: "bg-yellow-600",
  lime: "bg-lime-500",
  lightGreen: "bg-light-green-500",
  green: "bg-green-500",
  teal: "bg-teal-500",
  cyan: "bg-cyan-500",
  lightBlue: "bg-light-blue-500",
  blue: "bg-blue-500",
  indigo: "bg-indigo-500",
  deepPurple: "bg-deep-purple-500",
  purple: "bg-purple-500",
  pink: "bg-pink-500",
  red: "bg-red-500",
};

export const filledBgHoverColors: Record<Colors, string> = {
  blueGray: "hover:bg-blue-gray-700",
  gray: "hover:bg-gray-700",
  brown: "hover:bg-brown-700",
  deepOrange: "hover:bg-deep-orange-700",
  orange: "hover:bg-orange-700",
  amber: "hover:bg-amber-700",
  yellow: "hover:bg-yellow-700",
  lime: "hover:bg-lime-700",
  lightGreen: "hover:bg-light-green-700",
  green: "hover:bg-green-700",
  teal: "hover:bg-teal-700",
  cyan: "hover:bg-cyan-700",
  lightBlue: "hover:bg-light-blue-700",
  blue: "hover:bg-blue-700",
  indigo: "hover:bg-indigo-700",
  deepPurple: "hover:bg-deep-purple-700",
  purple: "hover:bg-purple-700",
  pink: "hover:bg-pink-700",
  red: "hover:bg-red-700",
};

export const filledBgFocusColors: Record<Colors, string> = {
  blueGray: "focus:bg-blue-gray-400",
  gray: "focus:bg-gray-400",
  brown: "focus:bg-brown-400",
  deepOrange: "focus:bg-deep-orange-400",
  orange: "focus:bg-orange-400",
  amber: "focus:bg-amber-400",
  yellow: "focus:bg-yellow-500",
  lime: "focus:bg-lime-400",
  lightGreen: "focus:bg-light-green-400",
  green: "focus:bg-green-400",
  teal: "focus:bg-teal-400",
  cyan: "focus:bg-cyan-400",
  lightBlue: "focus:bg-light-blue-400",
  blue: "focus:bg-blue-400",
  indigo: "focus:bg-indigo-400",
  deepPurple: "focus:bg-deep-purple-400",
  purple: "focus:bg-purple-400",
  pink: "focus:bg-pink-400",
  red: "focus:bg-red-400",
};

export const filledBgActiveColors: Record<Colors, string> = {
  blueGray: "active:bg-blue-gray-800",
  gray: "active:bg-gray-800",
  brown: "active:bg-brown-800",
  deepOrange: "active:bg-deep-orange-800",
  orange: "active:bg-orange-800",
  amber: "active:bg-amber-800",
  yellow: "active:bg-yellow-800",
  lime: "active:bg-lime-800",
  lightGreen: "active:bg-light-green-800",
  green: "active:bg-green-800",
  teal: "active:bg-teal-800",
  cyan: "active:bg-cyan-800",
  lightBlue: "active:bg-light-blue-800",
  blue: "active:bg-blue-800",
  indigo: "active:bg-indigo-800",
  deepPurple: "active:bg-deep-purple-800",
  purple: "active:bg-purple-800",
  pink: "active:bg-pink-800",
  red: "active:bg-red-800",
};

export const filledShadowColors: Record<Colors, string> = {
  blueGray: "shadow-md-blue-gray",
  gray: "shadow-md-gray",
  brown: "shadow-md-brown",
  deepOrange: "shadow-md-deep-orange",
  orange: "shadow-md-orange",
  amber: "shadow-md-amber",
  yellow: "shadow-md-yellow",
  lime: "shadow-md-lime",
  lightGreen: "shadow-md-light-green",
  green: "shadow-md-green",
  teal: "shadow-md-teal",
  cyan: "shadow-md-cyan",
  lightBlue: "shadow-md-light-blue",
  blue: "shadow-md-blue",
  indigo: "shadow-md-indigo",
  deepPurple: "shadow-md-deep-purple",
  purple: "shadow-md-purple",
  pink: "shadow-md-pink",
  red: "shadow-md-red",
};

export const filledShadowHoverColors: Record<Colors, string> = {
  blueGray: "hover:shadow-lg-blue-gray",
  gray: "hover:shadow-lg-gray",
  brown: "hover:shadow-lg-brown",
  deepOrange: "hover:shadow-lg-deep-orange",
  orange: "hover:shadow-lg-orange",
  amber: "hover:shadow-lg-amber",
  yellow: "hover:shadow-lg-yellow",
  lime: "hover:shadow-lg-lime",
  lightGreen: "hover:shadow-lg-light-green",
  green: "hover:shadow-lg-green",
  teal: "hover:shadow-lg-teal",
  cyan: "hover:shadow-lg-cyan",
  lightBlue: "hover:shadow-lg-light-blue",
  blue: "hover:shadow-lg-blue",
  indigo: "hover:shadow-lg-indigo",
  deepPurple: "hover:shadow-lg-deep-purple",
  purple: "hover:shadow-lg-purple",
  pink: "hover:shadow-lg-pink",
  red: "hover:shadow-lg-red",
};

export const colors: Record<Colors, string> = {
  blueGray: "text-blue-gray-500",
  gray: "text-gray-500",
  brown: "text-brown-500",
  deepOrange: "text-deep-orange-500",
  orange: "text-orange-500",
  amber: "text-amber-500",
  yellow: "text-yellow-600",
  lime: "text-lime-500",
  lightGreen: "text-light-green-500",
  green: "text-green-500",
  teal: "text-teal-500",
  cyan: "text-cyan-500",
  lightBlue: "text-light-blue-500",
  blue: "text-blue-500",
  indigo: "text-indigo-500",
  deepPurple: "text-deep-purple-500",
  purple: "text-purple-500",
  pink: "text-pink-500",
  red: "text-red-500",
};

export const outlineBorderColors: Record<Colors, string> = {
  blueGray: "border-blue-gray-500",
  gray: "border-gray-500",
  brown: "border-brown-500",
  deepOrange: "border-deep-orange-500",
  orange: "border-orange-500",
  amber: "border-amber-500",
  yellow: "border-yellow-600",
  lime: "border-lime-500",
  lightGreen: "border-light-green-500",
  green: "border-green-500",
  teal: "border-teal-500",
  cyan: "border-cyan-500",
  lightBlue: "border-light-blue-500",
  blue: "border-blue-500",
  indigo: "border-indigo-500",
  deepPurple: "border-deep-purple-500",
  purple: "border-purple-500",
  pink: "border-pink-500",
  red: "border-red-500",
};

export const outlineBgHoverColors: Record<Colors, string> = {
  blueGray: "hover:bg-blue-gray-50",
  gray: "hover:bg-gray-50",
  brown: "hover:bg-brown-50",
  deepOrange: "hover:bg-deep-orange-50",
  orange: "hover:bg-orange-50",
  amber: "hover:bg-amber-50",
  yellow: "hover:bg-yellow-50",
  lime: "hover:bg-lime-50",
  lightGreen: "hover:bg-light-green-50",
  green: "hover:bg-green-50",
  teal: "hover:bg-teal-50",
  cyan: "hover:bg-cyan-50",
  lightBlue: "hover:bg-light-blue-50",
  blue: "hover:bg-blue-50",
  indigo: "hover:bg-indigo-50",
  deepPurple: "hover:bg-deep-purple-50",
  purple: "hover:bg-purple-50",
  pink: "hover:bg-pink-50",
  red: "hover:bg-red-50",
};

export const outlineBorderHoverColors: Record<Colors, string> = {
  blueGray: "hover:border-blue-gray-700",
  gray: "hover:border-gray-700",
  brown: "hover:border-brown-700",
  deepOrange: "hover:border-deep-orange-700",
  orange: "hover:border-orange-700",
  amber: "hover:border-amber-700",
  yellow: "hover:border-yellow-700",
  lime: "hover:border-lime-700",
  lightGreen: "hover:border-light-green-700",
  green: "hover:border-green-700",
  teal: "hover:border-teal-700",
  cyan: "hover:border-cyan-700",
  lightBlue: "hover:border-light-blue-700",
  blue: "hover:border-blue-700",
  indigo: "hover:border-indigo-700",
  deepPurple: "hover:border-deep-purple-700",
  purple: "hover:border-purple-700",
  pink: "hover:border-pink-700",
  red: "hover:border-red-700",
};

export const outlineTextHoverColors: Record<Colors, string> = {
  blueGray: "hover:text-blue-gray-700",
  gray: "hover:text-gray-700",
  brown: "hover:text-brown-700",
  deepOrange: "hover:text-deep-orange-700",
  orange: "hover:text-orange-700",
  amber: "hover:text-amber-700",
  yellow: "hover:text-yellow-700",
  lime: "hover:text-lime-700",
  lightGreen: "hover:text-light-green-700",
  green: "hover:text-green-700",
  teal: "hover:text-teal-700",
  cyan: "hover:text-cyan-700",
  lightBlue: "hover:text-light-blue-700",
  blue: "hover:text-blue-700",
  indigo: "hover:text-indigo-700",
  deepPurple: "hover:text-deep-purple-700",
  purple: "hover:text-purple-700",
  pink: "hover:text-pink-700",
  red: "hover:text-red-700",
};

export const outlineBgActiveColors: Record<Colors, string> = {
  blueGray: "active:bg-blue-gray-100",
  gray: "active:bg-gray-100",
  brown: "active:bg-brown-100",
  deepOrange: "active:bg-deep-orange-100",
  orange: "active:bg-orange-100",
  amber: "active:bg-amber-100",
  yellow: "active:bg-yellow-100",
  lime: "active:bg-lime-100",
  lightGreen: "active:bg-light-green-100",
  green: "active:bg-green-100",
  teal: "active:bg-teal-100",
  cyan: "active:bg-cyan-100",
  lightBlue: "active:bg-light-blue-100",
  blue: "active:bg-blue-100",
  indigo: "active:bg-indigo-100",
  deepPurple: "active:bg-deep-purple-100",
  purple: "active:bg-purple-100",
  pink: "active:bg-pink-100",
  red: "active:bg-red-100",
};

export const mtInputColors = {
  blueGray: "mt-input-blue-gray-500",
  gray: "mt-input-gray-500",
  brown: "mt-input-brown-500",
  deepOrange: "mt-input-deep-orange-500",
  orange: "mt-input-orange-500",
  amber: "mt-input-amber-500",
  yellow: "mt-input-yellow-600",
  lime: "mt-input-lime-500",
  lightGreen: "mt-input-light-green-500",
  green: "mt-input-green-500",
  teal: "mt-input-teal-500",
  cyan: "mt-input-cyan-500",
  lightBlue: "mt-input-light-blue-500",
  blue: "mt-input-blue-500",
  indigo: "mt-input-indigo-500",
  deepPurple: "mt-input-deep-purple-500",
  purple: "mt-input-purple-500",
  pink: "mt-input-pink-500",
  red: "mt-input-red-500",
};

export const mtInputOutlineColors = {
  blueGray: "mt-input-outline-blue-gray-500",
  gray: "mt-input-outline-gray-500",
  brown: "mt-input-outline-brown-500",
  deepOrange: "mt-input-outline-deep-orange-500",
  orange: "mt-input-outline-orange-500",
  amber: "mt-input-outline-amber-500",
  yellow: "mt-input-outline-yellow-600",
  lime: "mt-input-outline-lime-500",
  lightGreen: "mt-input-outline-light-green-500",
  green: "mt-input-outline-green-500",
  teal: "mt-input-outline-teal-500",
  cyan: "mt-input-outline-cyan-500",
  lightBlue: "mt-input-outline-light-blue-500",
  blue: "mt-input-outline-blue-500",
  indigo: "mt-input-outline-indigo-500",
  deepPurple: "mt-input-outline-deep-purple-500",
  purple: "mt-input-outline-purple-500",
  pink: "mt-input-outline-pink-500",
  red: "mt-input-outline-red-500",
};

export const borderColors = {
  blueGray: "border-blue-gray-500",
  gray: "border-gray-500",
  brown: "border-brown-500",
  deepOrange: "border-deep-orange-500",
  orange: "border-orange-500",
  amber: "border-amber-500",
  yellow: "border-yellow-600",
  lime: "border-lime-500",
  lightGreen: "border-light-green-500",
  green: "border-green-500",
  teal: "border-teal-500",
  cyan: "border-cyan-500",
  lightBlue: "border-light-blue-500",
  blue: "border-blue-500",
  indigo: "border-indigo-500",
  deepPurple: "border-deep-purple-500",
  purple: "border-purple-500",
  pink: "border-pink-500",
  red: "border-red-500",
};
