
#
# Build Content
#
FROM node:16-alpine3.14 as build
WORKDIR /app
RUN adduser -D static
RUN apk add --no-cache python3-dev g++ gcc make musl-dev

# Better caching of package.json
ADD package.json /tmp/package.json
RUN cd /tmp && npm install 
RUN mkdir -p /app && cp -a /tmp/node_modules /app/

# Bring in everything now
COPY . .
RUN rm -f .proxyrc.json


EXPOSE 80

# Define entrypoint and default parameters
CMD ["npx", "parcel", "-p", "80", "public/index.html"]
