### Global Values if any ###
global: {}

### Sub Charts Specific Values ###
# Portal
ts-client-react:
  enabled: true

core-oauth-user:
  enabled: true
core-message:
  enabled: true
core-send-email:
  enabled: true
core-todo:
  enabled: true
core-user:
  enabled: true

publicapi-auth:
  enabled: true
publicapi-gpt:
  enabled: true
publicapi-file:
  enabled: true
publicapi-message:
  enabled: true
publicapi-todo:
  enabled: true
publicapi-user:
  enabled: true
publicapi-websocket:
  enabled: true

websocket-broadcast:
  enabled: true
websocket-file:
  enabled: true
websocket-message:
  enabled: true
websocket-todo:
  enabled: true
websocket-user:
  enabled: true

workers-user:
  enabled: true
workers-file:
  enabled: true

trigger-minio:
  enabled: true

#
#  External
#
minio:
  enabled: true
  fullnameOverride: minio
  extraEnvVars:
  - name: MINIO_NOTIFY_NATS_ENABLE_PRIMARY
    value: "on"
  - name: MINIO_NOTIFY_NATS_ADDRESS_PRIMARY
    value: "nats:4222"
  - name: MINIO_NOTIFY_NATS_SUBJECT_PRIMARY
    value: minioevents
  apiIngress:
    hostname: "minio"
    enabled: true
  auth:
    rootPassword: password
    #path: /minio_(.*)
    #pathType: Prefix
    #annotations:
    #  nginx.ingress.kubernetes.io/rewrite-target: $1

#  auth:
#    rootUser: admin
#    rootPassword: xyzzyxyzzy
nats:
  enabled: true
  fullnameOverride: nats
  #debug: { trace: true }
  #replicaCount: 0
  nats:
    logging:
      trace: true
redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  auth: { enabled: false }
