### Global Values if any ###
global: {}

### Sub Charts Specific Values ###
# Portal
ts-client-react:
  enabled: true
  image:
    version:

core-user:
  enabled: true
  image:
    version:
core-file:
  enabled: false
  image:
    version:
core-todo:
  enabled: true
  image:
    version:
core-oauth-user:
  enabled: true
  image:
    version:
core-send-email:
  enabled: true
  image:
    version:

publicapi-auth:
  enabled: true
  image:
    version:
publicapi-gpt:
  enabled: true
  image:
    version:
publicapi-websocket:
  enabled: true
  image:
publicapi-user:
  enabled: true
  image:
publicapi-todo:
  enabled: true
  image:
    version:
publicapi-file:
  enabled: true
  image:
    version:
publicapi-fileput:
  enabled: false
  image:
    version:

websocket-broadcast:
  enabled: true
  image:
    version:
websocket-todo:
  enabled: true
  image:
    version:
websocket-user:
  enabled: true
  image:
    version:

workers-user:
  enabled: true
  image:
    version:
workers-file:
  enabled: true
  image:
    version:

trigger-minio:
  enabled: true
  image:
    version:
#
#  External
#
minio:
  enabled: true
  fullnameOverride: minio
  extraEnvVars:
  - name: MINIO_NOTIFY_NATS_ENABLE_PRIMARY
    value: "on"
  - name: MINIO_NOTIFY_NATS_ADDRESS_PRIMARY
    value: "nats:4222"
  - name: MINIO_NOTIFY_NATS_SUBJECT_PRIMARY
    value: minioevents
  apiIngress:
    hostname: "minio"
    enabled: true
    #path: /minio_(.*)
    #pathType: Prefix
    #annotations:
    #  nginx.ingress.kubernetes.io/rewrite-target: $1

#  auth:
#    rootUser: admin
#    rootPassword: xyzzyxyzzy
nats:
  enabled: true
  fullnameOverride: nats
  #debug: { trace: true }
  #replicaCount: 0
  nats:
    logging:
      trace: false
redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  auth: { enabled: false }
