// Code generated by protoc-gen-twirp v8.1.1, DO NOT EDIT.
// source: core/eventbus.proto

package core

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ======================
// UserEventbus Interface
// ======================

type UserEventbus interface {
	UserChange(context.Context, *UserChangeEvent) (*EventbusEmpty, error)

	UserSecurity(context.Context, *UserSecurityEvent) (*EventbusEmpty, error)
}

// ============================
// UserEventbus Protobuf Client
// ============================

type userEventbusProtobufClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewUserEventbusProtobufClient creates a Protobuf client that implements the UserEventbus interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewUserEventbusProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) UserEventbus {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.eventbus", "UserEventbus")
	urls := [2]string{
		serviceURL + "UserChange",
		serviceURL + "UserSecurity",
	}

	return &userEventbusProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *userEventbusProtobufClient) UserChange(ctx context.Context, in *UserChangeEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "UserEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "UserChange")
	caller := c.callUserChange
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UserChangeEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserChangeEvent) when calling interceptor")
					}
					return c.callUserChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userEventbusProtobufClient) callUserChange(ctx context.Context, in *UserChangeEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userEventbusProtobufClient) UserSecurity(ctx context.Context, in *UserSecurityEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "UserEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "UserSecurity")
	caller := c.callUserSecurity
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UserSecurityEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserSecurityEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserSecurityEvent) when calling interceptor")
					}
					return c.callUserSecurity(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userEventbusProtobufClient) callUserSecurity(ctx context.Context, in *UserSecurityEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// UserEventbus JSON Client
// ========================

type userEventbusJSONClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewUserEventbusJSONClient creates a JSON client that implements the UserEventbus interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewUserEventbusJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) UserEventbus {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.eventbus", "UserEventbus")
	urls := [2]string{
		serviceURL + "UserChange",
		serviceURL + "UserSecurity",
	}

	return &userEventbusJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *userEventbusJSONClient) UserChange(ctx context.Context, in *UserChangeEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "UserEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "UserChange")
	caller := c.callUserChange
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UserChangeEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserChangeEvent) when calling interceptor")
					}
					return c.callUserChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userEventbusJSONClient) callUserChange(ctx context.Context, in *UserChangeEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userEventbusJSONClient) UserSecurity(ctx context.Context, in *UserSecurityEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "UserEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "UserSecurity")
	caller := c.callUserSecurity
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UserSecurityEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserSecurityEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserSecurityEvent) when calling interceptor")
					}
					return c.callUserSecurity(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userEventbusJSONClient) callUserSecurity(ctx context.Context, in *UserSecurityEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// UserEventbus Server Handler
// ===========================

type userEventbusServer struct {
	UserEventbus
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewUserEventbusServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewUserEventbusServer(svc UserEventbus, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &userEventbusServer{
		UserEventbus:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *userEventbusServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *userEventbusServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// UserEventbusPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const UserEventbusPathPrefix = "/twirp/core.eventbus.UserEventbus/"

func (s *userEventbusServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "UserEventbus")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "core.eventbus.UserEventbus" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "UserChange":
		s.serveUserChange(ctx, resp, req)
		return
	case "UserSecurity":
		s.serveUserSecurity(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *userEventbusServer) serveUserChange(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUserChangeJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUserChangeProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userEventbusServer) serveUserChangeJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UserChange")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UserChangeEvent)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserEventbus.UserChange
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UserChangeEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserChangeEvent) when calling interceptor")
					}
					return s.UserEventbus.UserChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling UserChange. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userEventbusServer) serveUserChangeProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UserChange")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UserChangeEvent)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserEventbus.UserChange
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UserChangeEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserChangeEvent) when calling interceptor")
					}
					return s.UserEventbus.UserChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling UserChange. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userEventbusServer) serveUserSecurity(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUserSecurityJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUserSecurityProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userEventbusServer) serveUserSecurityJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UserSecurity")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UserSecurityEvent)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserEventbus.UserSecurity
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UserSecurityEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserSecurityEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserSecurityEvent) when calling interceptor")
					}
					return s.UserEventbus.UserSecurity(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling UserSecurity. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userEventbusServer) serveUserSecurityProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UserSecurity")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UserSecurityEvent)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserEventbus.UserSecurity
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UserSecurityEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserSecurityEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserSecurityEvent) when calling interceptor")
					}
					return s.UserEventbus.UserSecurity(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling UserSecurity. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userEventbusServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *userEventbusServer) ProtocGenTwirpVersion() string {
	return "v8.1.1"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *userEventbusServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "core.eventbus", "UserEventbus")
}

// ======================
// TodoEventbus Interface
// ======================

type TodoEventbus interface {
	TodoChange(context.Context, *TodoChangeEvent) (*EventbusEmpty, error)
}

// ============================
// TodoEventbus Protobuf Client
// ============================

type todoEventbusProtobufClient struct {
	client      HTTPClient
	urls        [1]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewTodoEventbusProtobufClient creates a Protobuf client that implements the TodoEventbus interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewTodoEventbusProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) TodoEventbus {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.eventbus", "TodoEventbus")
	urls := [1]string{
		serviceURL + "TodoChange",
	}

	return &todoEventbusProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *todoEventbusProtobufClient) TodoChange(ctx context.Context, in *TodoChangeEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "TodoEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "TodoChange")
	caller := c.callTodoChange
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *TodoChangeEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*TodoChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*TodoChangeEvent) when calling interceptor")
					}
					return c.callTodoChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoEventbusProtobufClient) callTodoChange(ctx context.Context, in *TodoChangeEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// TodoEventbus JSON Client
// ========================

type todoEventbusJSONClient struct {
	client      HTTPClient
	urls        [1]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewTodoEventbusJSONClient creates a JSON client that implements the TodoEventbus interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewTodoEventbusJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) TodoEventbus {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.eventbus", "TodoEventbus")
	urls := [1]string{
		serviceURL + "TodoChange",
	}

	return &todoEventbusJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *todoEventbusJSONClient) TodoChange(ctx context.Context, in *TodoChangeEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "TodoEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "TodoChange")
	caller := c.callTodoChange
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *TodoChangeEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*TodoChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*TodoChangeEvent) when calling interceptor")
					}
					return c.callTodoChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *todoEventbusJSONClient) callTodoChange(ctx context.Context, in *TodoChangeEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// TodoEventbus Server Handler
// ===========================

type todoEventbusServer struct {
	TodoEventbus
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewTodoEventbusServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewTodoEventbusServer(svc TodoEventbus, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &todoEventbusServer{
		TodoEventbus:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *todoEventbusServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *todoEventbusServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// TodoEventbusPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const TodoEventbusPathPrefix = "/twirp/core.eventbus.TodoEventbus/"

func (s *todoEventbusServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "TodoEventbus")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "core.eventbus.TodoEventbus" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "TodoChange":
		s.serveTodoChange(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *todoEventbusServer) serveTodoChange(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveTodoChangeJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveTodoChangeProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *todoEventbusServer) serveTodoChangeJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "TodoChange")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(TodoChangeEvent)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.TodoEventbus.TodoChange
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *TodoChangeEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*TodoChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*TodoChangeEvent) when calling interceptor")
					}
					return s.TodoEventbus.TodoChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling TodoChange. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoEventbusServer) serveTodoChangeProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "TodoChange")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(TodoChangeEvent)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.TodoEventbus.TodoChange
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *TodoChangeEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*TodoChangeEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*TodoChangeEvent) when calling interceptor")
					}
					return s.TodoEventbus.TodoChange(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling TodoChange. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *todoEventbusServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 1
}

func (s *todoEventbusServer) ProtocGenTwirpVersion() string {
	return "v8.1.1"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *todoEventbusServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "core.eventbus", "TodoEventbus")
}

// ======================
// FileEventbus Interface
// ======================

type FileEventbus interface {
	FileUploaded(context.Context, *FileUploadEvent) (*EventbusEmpty, error)

	FileComplete(context.Context, *FileCompleteEvent) (*EventbusEmpty, error)
}

// ============================
// FileEventbus Protobuf Client
// ============================

type fileEventbusProtobufClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewFileEventbusProtobufClient creates a Protobuf client that implements the FileEventbus interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewFileEventbusProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) FileEventbus {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.eventbus", "FileEventbus")
	urls := [2]string{
		serviceURL + "FileUploaded",
		serviceURL + "FileComplete",
	}

	return &fileEventbusProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *fileEventbusProtobufClient) FileUploaded(ctx context.Context, in *FileUploadEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "FileEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "FileUploaded")
	caller := c.callFileUploaded
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *FileUploadEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileUploadEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileUploadEvent) when calling interceptor")
					}
					return c.callFileUploaded(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *fileEventbusProtobufClient) callFileUploaded(ctx context.Context, in *FileUploadEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *fileEventbusProtobufClient) FileComplete(ctx context.Context, in *FileCompleteEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "FileEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "FileComplete")
	caller := c.callFileComplete
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *FileCompleteEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileCompleteEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileCompleteEvent) when calling interceptor")
					}
					return c.callFileComplete(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *fileEventbusProtobufClient) callFileComplete(ctx context.Context, in *FileCompleteEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// FileEventbus JSON Client
// ========================

type fileEventbusJSONClient struct {
	client      HTTPClient
	urls        [2]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewFileEventbusJSONClient creates a JSON client that implements the FileEventbus interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewFileEventbusJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) FileEventbus {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.eventbus", "FileEventbus")
	urls := [2]string{
		serviceURL + "FileUploaded",
		serviceURL + "FileComplete",
	}

	return &fileEventbusJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *fileEventbusJSONClient) FileUploaded(ctx context.Context, in *FileUploadEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "FileEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "FileUploaded")
	caller := c.callFileUploaded
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *FileUploadEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileUploadEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileUploadEvent) when calling interceptor")
					}
					return c.callFileUploaded(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *fileEventbusJSONClient) callFileUploaded(ctx context.Context, in *FileUploadEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *fileEventbusJSONClient) FileComplete(ctx context.Context, in *FileCompleteEvent) (*EventbusEmpty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "FileEventbus")
	ctx = ctxsetters.WithMethodName(ctx, "FileComplete")
	caller := c.callFileComplete
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *FileCompleteEvent) (*EventbusEmpty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileCompleteEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileCompleteEvent) when calling interceptor")
					}
					return c.callFileComplete(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *fileEventbusJSONClient) callFileComplete(ctx context.Context, in *FileCompleteEvent) (*EventbusEmpty, error) {
	out := new(EventbusEmpty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// FileEventbus Server Handler
// ===========================

type fileEventbusServer struct {
	FileEventbus
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewFileEventbusServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewFileEventbusServer(svc FileEventbus, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &fileEventbusServer{
		FileEventbus:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *fileEventbusServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *fileEventbusServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// FileEventbusPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const FileEventbusPathPrefix = "/twirp/core.eventbus.FileEventbus/"

func (s *fileEventbusServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "core.eventbus")
	ctx = ctxsetters.WithServiceName(ctx, "FileEventbus")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "core.eventbus.FileEventbus" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "FileUploaded":
		s.serveFileUploaded(ctx, resp, req)
		return
	case "FileComplete":
		s.serveFileComplete(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *fileEventbusServer) serveFileUploaded(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveFileUploadedJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveFileUploadedProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *fileEventbusServer) serveFileUploadedJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "FileUploaded")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(FileUploadEvent)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.FileEventbus.FileUploaded
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *FileUploadEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileUploadEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileUploadEvent) when calling interceptor")
					}
					return s.FileEventbus.FileUploaded(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling FileUploaded. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *fileEventbusServer) serveFileUploadedProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "FileUploaded")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(FileUploadEvent)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.FileEventbus.FileUploaded
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *FileUploadEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileUploadEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileUploadEvent) when calling interceptor")
					}
					return s.FileEventbus.FileUploaded(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling FileUploaded. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *fileEventbusServer) serveFileComplete(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveFileCompleteJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveFileCompleteProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *fileEventbusServer) serveFileCompleteJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "FileComplete")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(FileCompleteEvent)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.FileEventbus.FileComplete
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *FileCompleteEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileCompleteEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileCompleteEvent) when calling interceptor")
					}
					return s.FileEventbus.FileComplete(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling FileComplete. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *fileEventbusServer) serveFileCompleteProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "FileComplete")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(FileCompleteEvent)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.FileEventbus.FileComplete
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *FileCompleteEvent) (*EventbusEmpty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*FileCompleteEvent)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*FileCompleteEvent) when calling interceptor")
					}
					return s.FileEventbus.FileComplete(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EventbusEmpty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EventbusEmpty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EventbusEmpty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EventbusEmpty and nil error while calling FileComplete. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *fileEventbusServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 2
}

func (s *fileEventbusServer) ProtocGenTwirpVersion() string {
	return "v8.1.1"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *fileEventbusServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "core.eventbus", "FileEventbus")
}

var twirpFileDescriptor1 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0xb3, 0x17, 0x8d, 0x0d, 0x9b, 0x4d, 0xea, 0x8d, 0xec, 0xc9, 0x07, 0x28, 0x09, 0x1e,
	0xbd, 0x49, 0x20, 0xc6, 0xab, 0xe2, 0xc1, 0x1b, 0xd0, 0x51, 0x49, 0x0a, 0xd3, 0x94, 0x62, 0xc2,
	0xeb, 0x18, 0x1f, 0xd4, 0xb4, 0xa5, 0x60, 0xf7, 0xd4, 0xe3, 0x7c, 0xff, 0xf4, 0x9b, 0x19, 0x20,
	0xb7, 0x1d, 0x2a, 0xc8, 0xe0, 0x1b, 0x46, 0xdd, 0xce, 0x13, 0x93, 0x0a, 0x35, 0xd2, 0xa3, 0x81,
	0xcc, 0xc3, 0xf4, 0x64, 0x7b, 0xe6, 0x09, 0x94, 0xcb, 0x57, 0xa0, 0x91, 0x63, 0x00, 0x3e, 0x7a,
	0x01, 0x0e, 0xdc, 0x9d, 0xc8, 0xb1, 0x5c, 0x9f, 0x97, 0x83, 0xd4, 0x4b, 0xfe, 0x73, 0x20, 0x49,
	0x3d, 0x81, 0xf2, 0x94, 0x56, 0x84, 0x98, 0xba, 0xf8, 0x6a, 0xc6, 0x4f, 0xa0, 0x29, 0xb3, 0x23,
	0xed, 0x8c, 0x1d, 0xdb, 0xe6, 0xf4, 0xcc, 0x82, 0x75, 0x58, 0x20, 0xa6, 0xcf, 0xce, 0xfb, 0x02,
	0xdd, 0xac, 0x7a, 0xbd, 0xd0, 0xf3, 0x85, 0xc9, 0x07, 0x11, 0xae, 0xfc, 0x8d, 0x24, 0xaf, 0xc8,
	0xf1, 0xff, 0x8e, 0xa6, 0x0e, 0x77, 0xb4, 0x67, 0xef, 0x38, 0xc6, 0xfb, 0x7b, 0x20, 0x49, 0xd5,
	0x0b, 0xd8, 0xc4, 0x4f, 0xae, 0xae, 0xa5, 0xc0, 0x86, 0x03, 0xf7, 0x6a, 0xfb, 0x01, 0xf7, 0x20,
	0xf2, 0x7c, 0xf3, 0xa0, 0xc0, 0x41, 0x0a, 0xd0, 0xe0, 0xcf, 0xdf, 0x4c, 0x3e, 0x88, 0x70, 0x3d,
	0xde, 0xbc, 0x5f, 0xb3, 0xec, 0xc1, 0x74, 0xb4, 0x57, 0xf6, 0x37, 0xde, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xb9, 0x59, 0xdd, 0xd2, 0x1f, 0x02, 0x00, 0x00,
}
