// Code generated by protoc-gen-twirp v8.1.1, DO NOT EDIT.
// source: core/send_email.proto

package core

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ==========================
// SendEmailService Interface
// ==========================

type SendEmailService interface {
	RegisterMessage(context.Context, *EmailRegisterParam) (*EmailOkResponse, error)

	PasswordChangeMessage(context.Context, *EmailPasswordChangeParam) (*EmailOkResponse, error)

	PasswordRecoveryMessage(context.Context, *EmailPasswordRecoveryParam) (*EmailOkResponse, error)

	InviteUserMessage(context.Context, *EmailInviteUserParam) (*EmailOkResponse, error)
}

// ================================
// SendEmailService Protobuf Client
// ================================

type sendEmailServiceProtobufClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewSendEmailServiceProtobufClient creates a Protobuf client that implements the SendEmailService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewSendEmailServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) SendEmailService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.send_email", "SendEmailService")
	urls := [4]string{
		serviceURL + "RegisterMessage",
		serviceURL + "PasswordChangeMessage",
		serviceURL + "PasswordRecoveryMessage",
		serviceURL + "InviteUserMessage",
	}

	return &sendEmailServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *sendEmailServiceProtobufClient) RegisterMessage(ctx context.Context, in *EmailRegisterParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "RegisterMessage")
	caller := c.callRegisterMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailRegisterParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailRegisterParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailRegisterParam) when calling interceptor")
					}
					return c.callRegisterMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceProtobufClient) callRegisterMessage(ctx context.Context, in *EmailRegisterParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *sendEmailServiceProtobufClient) PasswordChangeMessage(ctx context.Context, in *EmailPasswordChangeParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "PasswordChangeMessage")
	caller := c.callPasswordChangeMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailPasswordChangeParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordChangeParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordChangeParam) when calling interceptor")
					}
					return c.callPasswordChangeMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceProtobufClient) callPasswordChangeMessage(ctx context.Context, in *EmailPasswordChangeParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *sendEmailServiceProtobufClient) PasswordRecoveryMessage(ctx context.Context, in *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "PasswordRecoveryMessage")
	caller := c.callPasswordRecoveryMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordRecoveryParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordRecoveryParam) when calling interceptor")
					}
					return c.callPasswordRecoveryMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceProtobufClient) callPasswordRecoveryMessage(ctx context.Context, in *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *sendEmailServiceProtobufClient) InviteUserMessage(ctx context.Context, in *EmailInviteUserParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "InviteUserMessage")
	caller := c.callInviteUserMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailInviteUserParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailInviteUserParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailInviteUserParam) when calling interceptor")
					}
					return c.callInviteUserMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceProtobufClient) callInviteUserMessage(ctx context.Context, in *EmailInviteUserParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ============================
// SendEmailService JSON Client
// ============================

type sendEmailServiceJSONClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewSendEmailServiceJSONClient creates a JSON client that implements the SendEmailService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewSendEmailServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) SendEmailService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "core.send_email", "SendEmailService")
	urls := [4]string{
		serviceURL + "RegisterMessage",
		serviceURL + "PasswordChangeMessage",
		serviceURL + "PasswordRecoveryMessage",
		serviceURL + "InviteUserMessage",
	}

	return &sendEmailServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *sendEmailServiceJSONClient) RegisterMessage(ctx context.Context, in *EmailRegisterParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "RegisterMessage")
	caller := c.callRegisterMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailRegisterParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailRegisterParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailRegisterParam) when calling interceptor")
					}
					return c.callRegisterMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceJSONClient) callRegisterMessage(ctx context.Context, in *EmailRegisterParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *sendEmailServiceJSONClient) PasswordChangeMessage(ctx context.Context, in *EmailPasswordChangeParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "PasswordChangeMessage")
	caller := c.callPasswordChangeMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailPasswordChangeParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordChangeParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordChangeParam) when calling interceptor")
					}
					return c.callPasswordChangeMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceJSONClient) callPasswordChangeMessage(ctx context.Context, in *EmailPasswordChangeParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *sendEmailServiceJSONClient) PasswordRecoveryMessage(ctx context.Context, in *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "PasswordRecoveryMessage")
	caller := c.callPasswordRecoveryMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordRecoveryParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordRecoveryParam) when calling interceptor")
					}
					return c.callPasswordRecoveryMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceJSONClient) callPasswordRecoveryMessage(ctx context.Context, in *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *sendEmailServiceJSONClient) InviteUserMessage(ctx context.Context, in *EmailInviteUserParam) (*EmailOkResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithMethodName(ctx, "InviteUserMessage")
	caller := c.callInviteUserMessage
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *EmailInviteUserParam) (*EmailOkResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailInviteUserParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailInviteUserParam) when calling interceptor")
					}
					return c.callInviteUserMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sendEmailServiceJSONClient) callInviteUserMessage(ctx context.Context, in *EmailInviteUserParam) (*EmailOkResponse, error) {
	out := new(EmailOkResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===============================
// SendEmailService Server Handler
// ===============================

type sendEmailServiceServer struct {
	SendEmailService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewSendEmailServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewSendEmailServiceServer(svc SendEmailService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &sendEmailServiceServer{
		SendEmailService: svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *sendEmailServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *sendEmailServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// SendEmailServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const SendEmailServicePathPrefix = "/twirp/core.send_email.SendEmailService/"

func (s *sendEmailServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "core.send_email")
	ctx = ctxsetters.WithServiceName(ctx, "SendEmailService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}


	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "core.send_email.SendEmailService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "RegisterMessage":
		s.serveRegisterMessage(ctx, resp, req)
		return
	case "PasswordChangeMessage":
		s.servePasswordChangeMessage(ctx, resp, req)
		return
	case "PasswordRecoveryMessage":
		s.servePasswordRecoveryMessage(ctx, resp, req)
		return
	case "InviteUserMessage":
		s.serveInviteUserMessage(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *sendEmailServiceServer) serveRegisterMessage(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRegisterMessageJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRegisterMessageProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *sendEmailServiceServer) serveRegisterMessageJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RegisterMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(EmailRegisterParam)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.SendEmailService.RegisterMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailRegisterParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailRegisterParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailRegisterParam) when calling interceptor")
					}
					return s.SendEmailService.RegisterMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling RegisterMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) serveRegisterMessageProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RegisterMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(EmailRegisterParam)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.SendEmailService.RegisterMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailRegisterParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailRegisterParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailRegisterParam) when calling interceptor")
					}
					return s.SendEmailService.RegisterMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling RegisterMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) servePasswordChangeMessage(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePasswordChangeMessageJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePasswordChangeMessageProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *sendEmailServiceServer) servePasswordChangeMessageJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PasswordChangeMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(EmailPasswordChangeParam)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.SendEmailService.PasswordChangeMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailPasswordChangeParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordChangeParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordChangeParam) when calling interceptor")
					}
					return s.SendEmailService.PasswordChangeMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling PasswordChangeMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) servePasswordChangeMessageProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PasswordChangeMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(EmailPasswordChangeParam)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.SendEmailService.PasswordChangeMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailPasswordChangeParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordChangeParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordChangeParam) when calling interceptor")
					}
					return s.SendEmailService.PasswordChangeMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling PasswordChangeMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) servePasswordRecoveryMessage(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePasswordRecoveryMessageJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePasswordRecoveryMessageProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *sendEmailServiceServer) servePasswordRecoveryMessageJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PasswordRecoveryMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(EmailPasswordRecoveryParam)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.SendEmailService.PasswordRecoveryMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordRecoveryParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordRecoveryParam) when calling interceptor")
					}
					return s.SendEmailService.PasswordRecoveryMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling PasswordRecoveryMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) servePasswordRecoveryMessageProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PasswordRecoveryMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(EmailPasswordRecoveryParam)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.SendEmailService.PasswordRecoveryMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailPasswordRecoveryParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailPasswordRecoveryParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailPasswordRecoveryParam) when calling interceptor")
					}
					return s.SendEmailService.PasswordRecoveryMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling PasswordRecoveryMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) serveInviteUserMessage(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveInviteUserMessageJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveInviteUserMessageProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *sendEmailServiceServer) serveInviteUserMessageJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InviteUserMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(EmailInviteUserParam)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.SendEmailService.InviteUserMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailInviteUserParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailInviteUserParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailInviteUserParam) when calling interceptor")
					}
					return s.SendEmailService.InviteUserMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling InviteUserMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) serveInviteUserMessageProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InviteUserMessage")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(EmailInviteUserParam)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.SendEmailService.InviteUserMessage
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *EmailInviteUserParam) (*EmailOkResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*EmailInviteUserParam)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*EmailInviteUserParam) when calling interceptor")
					}
					return s.SendEmailService.InviteUserMessage(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*EmailOkResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*EmailOkResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *EmailOkResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *EmailOkResponse and nil error while calling InviteUserMessage. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sendEmailServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *sendEmailServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.1"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *sendEmailServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "core.send_email", "SendEmailService")
}

var twirpFileDescriptor1 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xad, 0xd3, 0x9f, 0x34, 0x37, 0x6d, 0xe2, 0xce, 0xd7, 0xaa, 0xf9, 0x2a, 0x15, 0x5a, 0x23,
	0xc4, 0x9f, 0x94, 0x4a, 0x61, 0x53, 0xc1, 0xaa, 0x6d, 0x4c, 0xf1, 0x82, 0xb4, 0x1a, 0xb7, 0x45,
	0x74, 0x81, 0x35, 0x8d, 0x6f, 0x8a, 0x49, 0x32, 0x36, 0x33, 0x6e, 0x10, 0x6f, 0xc0, 0x73, 0xf0,
	0x06, 0xac, 0x58, 0xb3, 0xe4, 0x89, 0xd8, 0xa2, 0x99, 0x71, 0x92, 0xa6, 0xb2, 0xaa, 0x48, 0x2c,
	0x80, 0x9d, 0xe7, 0xe4, 0xcc, 0x39, 0xf7, 0xdc, 0xf8, 0x5e, 0xc3, 0x5a, 0x3b, 0x16, 0xb8, 0x23,
	0x91, 0x87, 0x01, 0xf6, 0x59, 0xd4, 0xab, 0x27, 0x22, 0x4e, 0x63, 0x52, 0x55, 0x70, 0x7d, 0x0c,
	0x3b, 0x2d, 0x28, 0xb9, 0xea, 0xe1, 0x54, 0xa2, 0x20, 0xab, 0x30, 0xaf, 0xd1, 0x9a, 0xb5, 0x65,
	0x3d, 0x2c, 0x51, 0x73, 0x20, 0x04, 0xe6, 0x38, 0xeb, 0x63, 0xad, 0xa0, 0x41, 0xfd, 0x4c, 0xd6,
	0xa1, 0x78, 0x25, 0x51, 0x04, 0x51, 0x58, 0x9b, 0xd5, 0xf0, 0x82, 0x3a, 0x7a, 0xa1, 0xf3, 0xd9,
	0x82, 0x25, 0x2d, 0xb8, 0x97, 0x24, 0x1e, 0xef, 0xc4, 0xe4, 0x7f, 0x58, 0xbc, 0x12, 0xbd, 0xe0,
	0x82, 0x49, 0xcc, 0x64, 0x8b, 0x57, 0xa2, 0xb7, 0xcf, 0x24, 0xaa, 0x9f, 0x58, 0x92, 0x04, 0xd7,
	0xc4, 0x8b, 0x2c, 0x49, 0x5a, 0x4a, 0x7f, 0x1b, 0x96, 0x54, 0x91, 0x28, 0x4c, 0x99, 0x99, 0x49,
	0xd9, 0x60, 0x5a, 0x9f, 0xdc, 0x85, 0xec, 0x68, 0x04, 0xe6, 0x34, 0x03, 0x0c, 0xa4, 0x34, 0x9c,
	0xef, 0x16, 0x10, 0x4d, 0xa5, 0x78, 0x19, 0xc9, 0x14, 0xc5, 0x31, 0x13, 0xac, 0x4f, 0x76, 0x8d,
	0x6b, 0xc4, 0x3b, 0xb1, 0x2e, 0xa8, 0xdc, 0xd8, 0xac, 0xdf, 0xe8, 0x4a, 0xfd, 0x7a, 0x02, 0x5d,
	0x94, 0x8e, 0xb2, 0x0b, 0x25, 0x81, 0xed, 0x28, 0x89, 0x90, 0xa7, 0xba, 0xa2, 0x72, 0x63, 0x23,
	0xff, 0xaa, 0xea, 0x26, 0x1d, 0x93, 0x55, 0x1c, 0x81, 0x1d, 0x14, 0xc8, 0xdb, 0xa8, 0x7a, 0x66,
	0x8a, 0x2d, 0x8f, 0x30, 0x2f, 0x54, 0xbd, 0x4f, 0xe3, 0x2e, 0xf2, 0xda, 0xbc, 0xe9, 0xbd, 0x3e,
	0x38, 0x5f, 0x2d, 0xa8, 0x69, 0xc5, 0x63, 0x26, 0xe5, 0xc7, 0x58, 0x84, 0x07, 0xef, 0x18, 0xbf,
	0xc4, 0xbf, 0x39, 0x89, 0xf3, 0xc3, 0x82, 0x8d, 0x89, 0x9a, 0x29, 0xb6, 0xe3, 0x01, 0x8a, 0x4f,
	0xff, 0x60, 0xff, 0x7f, 0x5a, 0xb0, 0xaa, 0x15, 0x3d, 0x3e, 0x88, 0x52, 0x54, 0xba, 0xbf, 0x9b,
	0xa2, 0x01, 0x0b, 0xe6, 0x25, 0xd5, 0xef, 0xfc, 0xed, 0x11, 0x32, 0xe6, 0x9f, 0x48, 0xbe, 0x0d,
	0x55, 0x2d, 0x78, 0xd4, 0xa5, 0x28, 0x93, 0x98, 0x4b, 0x24, 0x15, 0x28, 0xc4, 0x5d, 0x9d, 0x76,
	0x91, 0x16, 0xe2, 0xae, 0xf3, 0xcd, 0x82, 0x8a, 0xe6, 0xf8, 0xc8, 0x53, 0x77, 0xa0, 0xec, 0x1e,
	0x40, 0x75, 0xe4, 0x1d, 0x5c, 0xdf, 0x25, 0x95, 0x11, 0x6c, 0xa6, 0x77, 0x13, 0xa0, 0x8f, 0x52,
	0xb2, 0x4b, 0x5d, 0x95, 0x99, 0xfe, 0x52, 0x86, 0x78, 0x21, 0x79, 0x06, 0x8b, 0x29, 0xf6, 0x93,
	0x1e, 0x4b, 0x51, 0xe7, 0xad, 0x34, 0xee, 0xe4, 0xe7, 0x3d, 0xc9, 0x58, 0x74, 0xc4, 0x9f, 0x22,
	0xf2, 0xe3, 0x0f, 0xb0, 0x3c, 0x71, 0x9b, 0x2c, 0x43, 0xe9, 0xb4, 0xd5, 0x74, 0x5f, 0x78, 0x2d,
	0xb7, 0x69, 0xcf, 0x90, 0xff, 0xa0, 0x7a, 0xea, 0xbb, 0x34, 0xa0, 0xee, 0xa1, 0xe7, 0x9f, 0xb8,
	0xd4, 0x6d, 0xda, 0x16, 0xb1, 0x61, 0x49, 0x83, 0x5e, 0xeb, 0xcc, 0x3b, 0x71, 0x9b, 0x76, 0x81,
	0xac, 0xc1, 0xca, 0xf1, 0x9e, 0xef, 0xbf, 0x3e, 0xa2, 0xcd, 0x80, 0xba, 0x07, 0x47, 0x67, 0x2e,
	0x7d, 0x63, 0xcf, 0xaa, 0xdb, 0x23, 0xf8, 0xe0, 0xe5, 0x5e, 0xeb, 0xd0, 0xb5, 0xe7, 0x1a, 0x5f,
	0x66, 0xc1, 0xf6, 0x91, 0x87, 0x59, 0xc3, 0xc4, 0x20, 0x6a, 0x23, 0x39, 0x87, 0xea, 0x70, 0x39,
	0xbd, 0x32, 0xd9, 0xc9, 0xbd, 0xfc, 0x9c, 0x13, 0x3b, 0x6c, 0x63, 0x2b, 0x9f, 0x34, 0xfe, 0xaf,
	0x9c, 0x19, 0xd2, 0x81, 0xb5, 0xc9, 0xa5, 0x31, 0x74, 0x78, 0x94, 0x7f, 0x39, 0x67, 0xc3, 0x4c,
	0xe5, 0xf3, 0x1e, 0xd6, 0x6f, 0x0e, 0xfa, 0xd0, 0xe9, 0xc9, 0xed, 0x4e, 0x13, 0x7b, 0x61, 0x2a,
	0xaf, 0xb7, 0xb0, 0x32, 0x1e, 0xc4, 0xa1, 0xcb, 0xfd, 0xfc, 0x8b, 0x37, 0x26, 0x76, 0x1a, 0xfd,
	0xfd, 0xd2, 0x79, 0xb1, 0xbe, 0xf3, 0x5c, 0xf1, 0x2e, 0x16, 0xf4, 0x07, 0xf3, 0xe9, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x51, 0xeb, 0xc6, 0xd3, 0x49, 0x07, 0x00, 0x00,
}
