FROM golang:1.20-alpine as builder
WORKDIR /build
ADD go.mod go.sum /build/
RUN go mod download
ADD . .
EXPOSE 14586
CMD ["./tilt-scripts/start.sh", "go", "run", "./cmd/compose/core/send_email/main.go"]
