FROM golang:1.19-alpine3.16 as builder
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
EXPOSE 14586
CMD ["./tilt-scripts/start.sh", "go", "run", "./cmd/compose/websocket/file/main.go"]
