name: Build Artifacts
on: workflow_call

jobs:
  build-app:
    environment: production
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ts-client-react
    
    steps:
      - uses: actions/checkout@v3 # setup the repository in the runner
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci # install dependencies
      - run: npm run build --if-present # build the project

      - uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: frontend
          path: ts-client-react/dist
          if-no-files-found: error
