on: push

jobs:
  test-app:
    environment: test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ts-client-react
    
    steps:
      - uses: actions/checkout@v3 # setup the repository in the runner
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci # install dependencies
      - npm: npm test

  test-go:
    environment: test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/go

    steps:
      - uses: actions/checkout@v3 # setup the repository in the runner
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - run: go version
      - run: go mod download # install packages
      - run: make test
