name: "Deploy production"

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/app_test.yaml@v1
  deploy:
    uses: ./.github/workflows/app_build.yaml@v1
  infra:
    uses: ./.github/workflows/terraform_apply.yaml@v1
