name: "Deploy updated code"
on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      AWS_DEFAULT_REGION: 
        required: true
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY: 
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    #defaults:
    #  run:
    #    working-directory: aws-tf

    steps:
      - uses: actions/checkout@v3 # setup the repository in the runner
      - uses: actions/download-artifact@v3
        id: frontend
        with:
          name: frontend
          path: ts-client-react/dist
      - uses: actions/download-artifact@v3
        with:
          name: backend-go
          path: src/go/build

      - name: Upload new Lambda functions
        run: |
          aws lambda update-function-code --function-name publicapi-auth --zip-file src/go/build/publicapi-auth.zip
          aws lambda update-function-code --function-name publicapi-file --zip-file src/go/build/publicapi-file.zip
          # aws lambda update-function-code publicapi-gpt --zip-file src/go/build/publicapi-gpt.zip
          aws lambda update-function-code --function-name publicapi-todo --zip-file src/go/build/publicapi-todo.zip
          aws lambda update-function-code --function-name publicapi-user --zip-file src/go/build/publicapi-user.zip
          aws lambda update-function-code --function-name publicapi-websocket --zip-file src/go/build/publicapi-websocket.zip
          aws lambda update-function-code --function-name websocket-file --zip-file src/go/build/websocket-file.zip
          aws lambda update-function-code --function-name websocket-todo --zip-file src/go/build/websocket-todo.zip
          aws lambda update-function-code --function-name websocket-user --zip-file src/go/build/websocket-user.zip
          aws lambda update-function-code --function-name core-oauth-user --zip-file src/go/build/core-oauth-user.zip
          aws lambda update-function-code --function-name core-send-email --zip-file src/go/build/core-send-email.zip
          aws lambda update-function-code --function-name core-todo --zip-file src/go/build/core-todo.zip
          aws lambda update-function-code --function-name core-user --zip-file src/go/build/core-user.zip
          aws lambda update-function-code --function-name workers-user --zip-file src/go/build/workers-user.zip
          aws lambda update-function-code --function-name workers-file --zip-file src/go/build/workers-file.zip
          aws lambda update-function-code --function-name trigger-s3 --zip-file src/go/build/trigger-s3.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: $${ secrets.AWS_DEFAULT_REGION }}
