name: "Terraform Deploy"
on: 
  push:
    branches:
    - main
    paths:
    - 'aws-tf/**'
# workflow_call:
#   inputs:
#     environment:
#       required: true
#       type: string
#   secrets: 
#     TF_API_TOKEN: 
#       required: true

jobs:
  deploy:
    #environment: ${{ inputs.environment }}
    environment: production
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: aws-tf

    steps:
      - uses: actions/checkout@v3 # setup the repository in the runner
      - uses: actions/download-artifact@v3
        id: frontend
        with:
          name: frontend
          path: ts-client-react/dist
      - uses: actions/download-artifact@v3
        with:
          name: backend-go
          path: src/go/build
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate module and provider bindings
        run: npx cdktf-cli get
      - run: npm ci

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.3.9
          cdktfVersion: 0.15.5
          stackName: aws-tf
          # mode: plan-only
          mode: auto-approve-apply
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          workingDirectory: aws-tf
