name: "Run Tests"
on: workflow_call


jobs:
  test-go:
    environment: test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/go

    steps:
      - uses: actions/checkout@v3 # setup the repository in the runner
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - run: go version
      - run: go mod download # install packages
      - run: make test
